### PR TITLE
doc: 📚 initial mkdocs-material website config with dark/light theme added

### PR DESCRIPTION
**Pull request by onuralpszr**
Hello @merveenoyan; as we speak here is my PR for docs :) 

Initial doc config and github action

Light theme

image

Dark theme

image

### CODE REVIEW

**Comment by merveenoyan** [comment]
This looks very cool! 👌

**Comment by merveenoyan** [comment]
@onuralpszr would be great to post about this tomorrow, I think since you added it you could post with link and I can reshare :)

**Comment by onuralpszr** [comment]
@merveenoyan  could you check the repo settings you need to enable publish so we can see the website online as well? I see my code push to repo but I don't see website online because of settings needs to be enabled

**Comment by onuralpszr** [comment]
> @onuralpszr would be great to post about this tomorrow, I think since you added it you could post with link and I can reshare :)

I will do it once I see the website online 👍  thank you for your kind suggestion

**Comment by onuralpszr** [comment]
friendly ping @merveenoyan  and good morning please check the publish mechanism in repo settings (you should be enable that easily)

**Pull request merged**
